/** Compiler silently writes 4 function if they are not explicitly declared:
 * ----C++ 03:
 * 1. Default Constructor( only if there is no constructor declared)
 * 2. Copy Constructor(generated only if no 5,6 declared by user) + (c++11 3,4)
 * 3. Copy Assiment operator(generated only if 5,6 not declared by user) + (c++11 2,4)
 * 4. Destructor
 * 
 * ----C++ 11:
 * 5. Move Constructor( only if 2,3,4,6 not declared by user)
 * 6. Move Assigment Operator( generated only 2,3,4,5 not declared by user)
 *
 */

#include <iostream>

using namespace std;

///-example1-
class Cat { //(3,4 c++3),(4 c++11) generated by compiler
public:
	Cat(const Cat&) {}; // copy constructor
};

///-example2-
class Duck {//4 generetaed by compiler
public:
	Duck(Duck&& ) {}; // move constructor
};

///-example3-
class Frog { //4 generated by compiler
public:
	Frog(Frog&&,int=0) {}; // move constructor
	Frog(int=0) {}; //default constructor
	Frog(const Frog&,int=0) {};// Copy constructor
};

///-example4-
class Cow { //(1,2,4 c++3), (1,4 c++11) generated by compiler
public:
	Cow& operator=(const Cow&) = delete;
	Cow(const Cow&) = default;
};

int main() {

	return 0;
}
